server.port=8072
eureka.instance.hostname=localhost
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka/
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true
management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=gateway
logging.config=classpath:log4j2.xml
logging.level.com.netflix=WARN
logging.level.org.springframework.web=WARN
logging.level.com.optimagrowth=DEBUG

management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.endpoints.web.exposure.include=*
